server:
    servlet:
        contextPath: /api

env:
    database:
        schema:
            roles:
                filePath: database/tests-e2e/roles.json
            membership:
                filePath: database/tests-e2e/memberships.json
    microservices:
        teams:
            baseUrl: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/teams
        users:
            baseUrl: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/users
